[WIP] TOR-999 - aikuisten perusopetuksen rahoitusrapsa 2
Opetushallitus/koski pull request #1016
Opened 2020-11-12 15:41 UTC by tzaeru

2020-11-17 10:15 UTC, suarela requested changes
Voisiko commit viestit muuttaa kuvaamaan tehtyjä muutoksia? `queryy` ei kerro juuri mitään

2020-11-17 10:15 UTC, suarela commented on src/main/scala/fi/oph/koski/raportit/RaportitService.scala
>        case application.organisaatioService.ostopalveluRootOid =>
miksi tässä matchataan ostopalvelu oideihin? vain esiopetuksen opiskeluoikeuden oppilaitokset voivat olla sellaisia, että opiskeluoikeuden koulutustoimijan organisaatiohierarkian alta ei löydy opiskeluoikeuden oppilaitosta. sen takia on keksitty tuo ostopalveluRootOid, että käyttöliittymästä voi valita dropdownista kaikki organisaatiohierarkiasta poikkeavat opiskeluoikeudet

2020-11-17 10:15 UTC, suarela commented on src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenEiRahoitustietoaKurssit.scala
> +              coalesce(r_osasuoritus.koulutusmoduuli_kurssin_tyyppi, '') as suorituksen_tyyppi
voisiko tämä olla tyypiltään vain Option[String] jos sitä ei ole olemassa. Nonet osataan käsitellä exceleissä tyhjinä sarakkeina

2020-11-17 10:15 UTC, suarela commented on src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenOpiskeluoikeudenUlkopuolisetKurssit.scala
> +                select 1
mikä tämän selectin pointti on? katsotaan, että opiskeluoikeuden oidilla löytyy ainakin yksi aikajakso? kaikilla opiskeluoikeuksilla on ainaskin yksi rivi aikajakso-taulussa

2020-11-17 10:15 UTC, suarela commented on src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenOppimääränKurssikertymät.scala
> +            select 1
mainittu aikaisemmin

2020-11-17 10:15 UTC, suarela commented on src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenOppimääränKurssikertymät.scala
> +        join r_opiskeluoikeus_aikajakso aikajakso on aikajakso.opiskeluoikeus_oid = oo_opiskeluoikeus_oid
tupla joini?

2020-11-17 10:15 UTC, suarela commented on src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenEiRahoitustietoaKurssit.scala
> +                select 1
mainittu aikaisemmin

2020-11-17 10:15 UTC, suarela commented on src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenAineopiskelijoidenKurssikertymät.scala
> +            select 1
täällä kans sama

2020-11-17 10:15 UTC, suarela commented on src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenOppimääränKurssikertymät.scala
> +      yhteensäTunnistettujaSuorituksiaRahoituksenPiirissä = r.rs.getInt("yhteensäTunnistettujaSuorituksiaRahoituksenPiirissä"),
voisiko resultsettien nimet käyttää samaa konventiota? nyt on käytössä sekaisin camel casea ja snake casea. muualla snake case taitaa olla käytössä

2020-11-17 13:38 UTC, tzaeru commented on src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenEiRahoitustietoaKurssit.scala
> +              coalesce(r_osasuoritus.koulutusmoduuli_kurssin_tyyppi, '') as suorituksen_tyyppi
En oo varma miten tän tekee nätisti ton ResultSetin lukemisen kanssa (kun luetaan tyyliin `r.rs.getString("suorituksen_tyyppi")`)

2020-11-19 12:51 UTC, tzaeru commented
retest this please

2020-11-20 14:06 UTC, merged