TOR-xxxx: Älä yritä hakea lapsiorganisaatioiden dataa Valppaan käliin
Opetushallitus/koski pull request #1364
Opened 2021-05-14 11:28 UTC by AleksiAhtiainen

Esim. kunnilla hajoaa.

2021-05-14 13:45 UTC, AleksiAhtiainen commented
Tämän fiksin lisäksi pitää varmaan muuttaa organisaatiovalitsinta silleen, että se listaa myös kaikki lapsiorganisaatiot, jotka ovat oppilaitoksia. Ja samalla ehkä toistaiseksi filtteröidä organisaatiovalitsimessa näkymään pelkät oppilaitokset, eikä kuntia.

Ei pitäisi olla iso homma, ja sen jälkeen myös kunta-tasolle annetut hakeutumisen valvonnan oikeudet alkavat toimia käyttäjän kannalta fiksusti.

2021-05-17 07:25 UTC, AleksiAhtiainen commented
> Tämän fiksin lisäksi pitää varmaan muuttaa organisaatiovalitsinta silleen, että se listaa myös kaikki lapsiorganisaatiot, jotka ovat oppilaitoksia. Ja samalla ehkä toistaiseksi filtteröidä organisaatiovalitsimessa näkymään pelkät oppilaitokset, eikä kuntia.
> 
> Ei pitäisi olla iso homma, ja sen jälkeen myös kunta-tasolle annetut hakeutumisen valvonnan oikeudet alkavat toimia käyttäjän kannalta fiksusti.

Tämä on nyt toteutettu.

Organisaatiohierarkian filtteröinnin ja lapsien käsittelyn voisi siirtää backendin puolelle: käyttöliittymälle lähetetään tällä hetkellä kaikki hierarkian datat, mistä varmaan n. 90% se ei käytä eikä tarvitse.

2021-05-17 08:30 UTC, ilkkahanninen requested changes
Hyvältä näyttää. Lisäisin tosiaan vain tuon useMemon tuonne. Sen jälkeen ei tarvitse edes stressata, onko tuo rekursiohässäkkä tarpeeksi vikkelä, koska se ajettaisiin käytännössä vain kerran per sivun avaaminen. Mun mielestä ei tarvitse tuota filtteröintiosuutta myöskään siirtää bäkkärin puolelle.

2021-05-17 08:30 UTC, ilkkahanninen commented on valpas-web/src/views/hakutilanne/HakutilanneView.tsx
>      const organisaatiot = getOrganisaatiot(props.kayttooikeusroolit)
Tässä vois käyttää memoisaatiota, koska tuolla getOrganisaation alla on sen verran paljon rekursiota ja laskentaa, eli `const organisaatiot = useMemo(() => getOrganisaatiot(props.kayttooikeusroolit), [props.kayttooikeusroolit])`

2021-05-17 08:46 UTC, merged