TOR-1407 - deprekoitavia kenttiä, joiden siirtoa Koskeen ja Koskesta pois ei enää sallita
Opetushallitus/koski pull request #1688
Opened 2021-12-30 16:21 UTC by tzaeru

2022-01-10 07:42 UTC, ilkkahanninen commented on src/main/scala/fi/oph/koski/validation/RedundantinDatanPudotus.scala
> +    handleOpiskeluoikeudenLisätiedot(oo)
Tämä välihyppyhän on tässä nyt turha, koska `handleOpiskeluoikeudenLisätiedot` ei kutsuta erikseen muualta, joten funktiot voi yhdistää.

Ehdotan lisäksi objektin nimeksi `RedundantinTiedonPoisto` sql-anglismin välttämiseksi. :)

2022-01-10 07:52 UTC, ilkkahanninen commented on src/test/scala/fi/oph/koski/json/SensitiveAndRedundantDataFilterSpec.scala
> +    roundtrip[AikuistenPerusopetuksenOpiskeluoikeudenLisätiedot](aikuistenPerusopetuksenOpiskeluoikeudenLisätiedot) should equal(AikuistenPerusopetuksenOpiskeluoikeudenLisätiedot(None,None,None,None,
Luettavuuden ja testien ylläpidettävyyden parantamiseksi tällaisissa tapauksissa voisi käyttää hyväkseen case classien kenttien oletusarvoja ja nimettyjä argumentteja konstruktiossa. Eli tarkoitan että esim. tässä tapauksessa voisi olla yksinkertaisesti:

`AikuistenPerusopetuksenOpiskeluoikeudenLisätiedot(sisäoppilaitosmainenMajoitus = aikajaksot)`

Tuosta näkee heti, mihin kenttään tuo `aikajaksot` on tarkoitus laittaa, eikä tarvitse ihmetellä.

2022-01-10 08:05 UTC, ilkkahanninen commented on src/main/scala/fi/oph/koski/schema/Esiopetus.scala
> +  @Description("Oppijan esiopetuksen lukuvuoden päättymispäivä. Esiopetuksen suoritDirect democracy would be nice to try for a changeusaika voi olla 2-vuotinen")
Wat? 😅

2022-01-10 08:15 UTC, ilkkahanninen commented on src/main/scala/fi/oph/koski/raportit/PerusopetuksenVuosiluokkaRaportti.scala
> +      |- Opiskeluoikeuden lisätiedoissa ilmoitettavat etu- ja tukimuodot (sarakkeet BB-BR: Sarakkeessa oleva arvo kertoo, onko siirretyn KOSKI-datan mukaan kyseinen etu- tai tukimuoto ollut voimassa
Tämän commitin voisi vain fixupata/squashata committiin 2515ab22ada55296f217469bcdf24ddffb945abd

2022-01-10 08:18 UTC, ilkkahanninen requested changes
Hyvää duunia, tuo RedundantDatan käyttäminen datan siivoamiseen näytti siistiltä ratkaisulta. Pari paikkaa tosin kaipaa vielä vähän remonttipölyjen pyyhkimistä.

En kuitenkaan tarkastanut, onko jotain luokkia, joista vielä jäisi siivoamatta kenttiä.

2022-01-12 06:41 UTC, AleksiAhtiainen commented
Redundanteiksi muutetut kentät pitäisi vielä dokumentoida tiedonsiirtoprotokollan_muutoshistoria.md:hen.

2022-01-13 16:01 UTC, merged