[WIP] TOR-1685 ESH osasuoritustietomalli
Opetushallitus/koski pull request #2113
Opened 2022-10-17 12:34 UTC by AleksiAhtiainen

Ks. commit-viestit.

2022-11-08 10:04 UTC, AleksiAhtiainen commented on src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoader.scala
> +      case "europeanschoolofhelsinki" => true
Tästä pitää vielä poistaa nursery-luokat, jotka ovat ESH:ssa 4-5 v suoritettavia, eivätkä kelpaa oppivelvollisuuden suorittamiseen.

2022-11-08 11:15 UTC, alehuo requested changes
Hyvältä näyttää! Lisäsin muutaman kommentin koodistoista, jotka kannattaa vilkaista. Tämä alkaa näyttää jo aika valmiilta.

2022-11-08 11:15 UTC, alehuo commented on src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedot.scala
> +    case esh: EuropeanSchoolOfHelsinkiOpiskeluoikeus => esh.suoritukset.filter(_.alkamispäivä.isDefined).sortBy(_.alkamispäivä).lastOption match {
Voinee yhdistää alempana olevan, international schoolille tehdyn toteutuksen kanssa käyttämällä syntaksia `case something: InternationalSchoolOpiskeluoikeus | EuropeanSchoolOfHelsinkiOpiskeluoikeus`

2022-11-08 11:15 UTC, alehuo commented on src/main/scala/fi/oph/koski/schema/EuropeanSchoolOfHelsinki.scala
> +    koodiarvo == "0" || koodiarvo == "0.5" || koodiarvo == "10" || koodiarvo.matches("^[123456789]\\.[05]$")
Vika Regex:
```scala
koodiarvo.matches("^[1-9]\\.[05]$")
```

2022-11-08 11:15 UTC, alehuo commented on src/main/scala/fi/oph/koski/schema/EuropeanSchoolOfHelsinki.scala
> +    koodiarvo == "0" || koodiarvo == "10" || koodiarvo.matches("^0\\.[123456789]$") || koodiarvo.matches("^[123456789]\\.\\d$")
```scala
koodiarvo == "0" || koodiarvo == "10" || koodiarvo.matches("^0\\.[1-9]$") || koodiarvo.matches("^[1-9]\\.\\d$")
```

2022-11-08 11:15 UTC, alehuo commented on web/app/editor/DateEditor.jsx
> +  model.optional &&
Jos näitä samoja tarkastuksia tehdään tulevaisuudessa lisää erityyppisille suorituksille, kannattaa toiminnallisuus splitata omaan funktioonsa, jotta vältytään copypastelta.

2022-11-08 12:34 UTC, AleksiAhtiainen commented on src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedot.scala
> +    case esh: EuropeanSchoolOfHelsinkiOpiskeluoikeus => esh.suoritukset.filter(_.alkamispäivä.isDefined).sortBy(_.alkamispäivä).lastOption match {
Ei taida pystyä tätä tekemään, koska Scala ei tunnista sopivaa tyyppiä something:lle

2022-11-09 06:37 UTC, alehuo requested changes

2022-11-09 06:37 UTC, alehuo commented on src/main/resources/mockdata/koodisto/koodistot/europeanschoolofhelsinkilapsioppimisalue.json
> +    "kuvaus" : "European School of Helsinki Primary lapsi -oppimisalue"
Typo tässä?

2022-11-09 07:14 UTC, merged