[WIP] Tor-999 - lisätty testejä
Opetushallitus/koski pull request #945
Opened 2020-09-14 14:58 UTC by tzaeru

2020-09-16 11:29 UTC, tzaeru commented
retest this please

2020-09-22 10:48 UTC, AleksiAhtiainen requested changes
En koodista huomaa mitään, mutta en saa paikallisesti toimimaan raportti-sivua.

Tein näin: 
(1) Loggasin sisään esiopetus -mock -käyttäjällä
(2) klikkasin Raportit-tabiä
(3) tapahtuu tällainen virhe:

![image](https://user-images.githubusercontent.com/6376268/93873175-ed721180-fcd9-11ea-9d4e-129e0df70938.png)

2020-09-22 10:59 UTC, AleksiAhtiainen commented on web/test/spec/RaportitSpec.js
> +      before(page.valitseOrganisaatio('Jyväskylän normaalikoulu'), page.syötäPäivämäärä('1.1.2007'), page.luoRaportti())
`page.organisaatioHakuNäkyvissä()).to.equal(true)` pitäisi mielestäni tehdä (myös) sisemmän describe:n before:ssa: muuten sisemmän describe:n it-testiä ei voi ajaa luotettavasti yksinään, kun hakukenttä ei välttämättä ole vielä auki.

2020-09-22 11:00 UTC, AleksiAhtiainen commented
> En koodista huomaa mitään, mutta en saa paikallisesti toimimaan raportti-sivua.
> 
> Tein näin:
> (1) Loggasin sisään esiopetus -mock -käyttäjällä
> (2) klikkasin Raportit-tabiä
> (3) tapahtuu tällainen virhe:
> 

Tämä ratkesi: minulla ei ollut paikallinen raportointikanta ajantasalla, `scripts/local-reset-raportointikanta.sh` auttoi.

2020-09-22 11:07 UTC, AleksiAhtiainen approved these changes
Ks. kommentti poiskommentoidun testin before-lohkosta

2020-09-25 09:22 UTC, merged